gold_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Wir nutzen einen Pfad, der relativ zum dbt-Projektordner funktioniert
      path: "data/gold_market.duckdb"
      schema: main
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('GCP_DATASET', 'gold_analytics') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_KEYFILE_PATH', 'auth/service_account.json') }}"
      location: EU
      priority: interactive
