version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: gold_prices
      - name: etf_flows
      - name: gold_stocks
      - name: gdt_demand
      - name: mining_production
      - name: gold_premiums
      - name: central_bank_holdings
      - name: dxy
      - name: sp500
      - name: yield_10y
      - name: crude_oil
